version: "3.8"

services:
  
  jwt:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure   
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - "4546:8000"
    environment:
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8081,server=y,suspend=n
      SPRING_APPLICATION_JSON: '{"":""}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: